extends CardDisplayProperties
class_name EffectDisplayProperties

enum SymbolFlags {BUST_DOWN, BUST_UP, CARD_ADD, CARD_DESTROY, CARD_DISCARD, CARD_DRAW, CARD_CREATE, DISCARD_SELF, CARD_GRAFT, MANA_MINUS, MANA_PLUS, MULTI_MANA_MINUS, MULTI_MANA_PLUS, SHIELD_UP, SHIELD_DOWN, SHIELD_MULTI, SWORD_UP, SWORD_DOWN, SWORD_MULTI, X_UP, X_DOWN, X_UNKNOWN, MULTI_MODIFIER, CONDITIONAL, CHOOSE}

@export var cardEffectSymbolFlag: SymbolFlags